filetype plugin on
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'
set noexpandtab
syn on
filetype on
let Tlist_Auto_Open=1
au BufNewFile,BufRead SCons* set filetype=scons
autocmd QuickFixCmdPost [^l]* nested cwindow

augroup python_files
	autocmd FileType python compiler pylint
	autocmd!
	autocmd FileType python setlocal noexpandtab
	autocmd FileType python set tabstop=8
	autocmd FileType python set softtabstop=8
	autocmd FileType python set shiftwidth=8
augroup END

let g:syntastic_python_pylint_args = ""
let g:syntastic_cpp_checkers = ["cppcheck"]

python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
